source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

target 'NPDispatcher_Example' do
  pod 'NPDispatcher', :path => '../'

  target 'NPDispatcher_Tests' do
    inherit! :search_paths

  end
end
